name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-client:
    name:  Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm run install
      - name: Build
        run: npm run build
