name: ESLint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: cd server && npm ci
      - run: cd server && npm run lint
      - run: cd client && npm ci
      - run: cd client && npm run lint
