name: ESLint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install server dependencies
        run: cd server && npm ci
      - name: Lint server
        run: cd server && npm run lint

      - name: Install client dependencies
        run: cd client && npm ci
      - name: Lint client
        run: cd client && npm run lint
