name: ESLint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-server:
    name: Lint Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: cd server && npm ci
      - name: Lint
        run: cd server && npm run lint

  lint-client:
    name: Lint Client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: cd client && npm ci
      - name: Lint
        run: cd client && npm run lint
